### ISSUE TITLE
Push Clients need to be able to reach the backend VIP

### ISSUE THREAD

**Issue by markan** [chef-boneyard/omnibus-pushy#69]
A push client needs to be able to reach the backend VIP to connect to the push jobs server. This causes trouble in some network topologies, and is unlike any other part of chef server.

A workaround would be to forward the push jobs ports from a publicly available IP to the backend VIP. The actual server has the 'server_name' config option, which sets what address the clients use to connect to. (https://github.com/opscode/opscode-pushy-server/blob/master/apps/pushy/src/pushy_config_resource.erl#L81)

However, the omnibus cookbook (https://github.com/opscode/omnibus-pushy/blob/master/files/pushy-server-cookbooks/opscode-pushy-server/templates/default/opscode-pushy-server.config.erb#L83) hardcodes the node['pushy']['opscode-pushy-server']['vip'] as the server_name. That attribute is also used by the FE nginx config to forward the client http requests, and needs to be the internally routable address. 
Instead we should change the template to allow this to be separately configured as a user settable attribute.

Longer term, we should move the push service to the frontend; that will remove a user pain point.

**Comment by jeremiahsnapp** [comment]
I just wanted to add that the following instructions can be used as the workaround solution until the improvements make their way into new releases.

On both the primary and secondary backend Chef servers open the file `/opt/opscode-push-jobs-server/embedded/cookbooks/opscode-pushy-server/templates/default/opscode-pushy-server.config.erb` to line 82 and set the server_name to the NAT IP that forwards to your backend VIP.

```
{pushy, [
          {server_name, "198.x.x.x" },
```

Then on both the primary and secondary backend Chef servers run `opscode-push-jobs-server-ctl reconfigure` to apply that change.

**Comment by manderson26** [comment]
Merged, will be in 1.3
